services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tournament_service
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  tournament-service:
    build: .
    container_name: tournament-service
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      # set server environment to "docker" to run the
      # service server on the specific docker container address
      - SERVER_ENV=docker

